### ISSUE TITLE
node generate not working

### ISSUE THREAD

**Issue by mmoheng** [hermanho/MMM-GooglePhotos#108]
pi@raspberrypi:~/MMM-GooglePhotos $ node generate_token.js
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'moment'
Require stack:
- /home/pi/MMM-GooglePhotos/GPhotos.js
- /home/pi/MMM-GooglePhotos/generate_token.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MMM-GooglePhotos/GPhotos.js:12:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MMM-GooglePhotos/GPhotos.js',
    '/home/pi/MMM-GooglePhotos/generate_token.js'

**Comment by aneaville** [comment]
The helper module appears to be missing. 
Was this a fresh install or an older install that added the google photos module?

There are other issues that deal with this. Please search closed issues(specifically #61) to see if any help your situation.

**Comment by mmoheng** [comment]
This was on a fresh install it did work the very first time I ever did it but would not add new pics

**Comment by aneaville** [comment]
Can you elaborate on "but would not add new pics"? 
The album is scanned every hour.  I find that users add pics to the album and expect them to show up immediately.

If it was working originally, what did you change that lead up this error?

**Comment by mmoheng** [comment]
i added pics to the album when i went to bed and by 10am they where not loaded in i even waited 24 hours nothing would load i will do a fresh install and see what it tells me

**Comment by mmoheng** [comment]
Just did a fresh install and i am getting this message when i try to node generate_token.js




[GPHOTOS:AUTH] Token is expired.
(node:9846) UnhandledPromiseRejectionWarning: Error: unauthorized_client
    at createError (/home/pi/MagicMirror/MMM-GooglePhotos/node_modules/google-auth-library/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/pi/MagicMirror/MMM-GooglePhotos/node_modules/google-auth-library/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/MMM-GooglePhotos/node_modules/google-auth-library/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9846) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aneaville** [comment]
Do you have an old token.json in the directory? Try deleting that and try again.

**Comment by aneaville** [comment]
I'm going to close the issue. If you would still like assistance, feel free to reopen.
