### ISSUE TITLE
Getting index.js:29 error

### ISSUE THREAD

**Issue by nawaidrana** [hermanho/MMM-GooglePhotos#26]
I updated npm, updated my linux system, magicmirror is runnign fine, but after I installed MMM-Googlephotos, I cant seem to run it, I deleted MMM-GooglePhotos folder and reinstalled, but same issue. Can you please help? I did paste credentials.json after I installed MMM-GooglePhotos

node auth_and_test.js
/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/open/index.js:29
		...options
		^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GooglePhotos/auth.js:6:13)

**Comment by eouia** [comment]
I think you just did `git pull`. `npm install` is also needed to update this module.

**Comment by nawaidrana** [comment]
I did npm install within MMM-GooglePhotos folder, it goes through fine with one warn message but installs successfully

**Comment by nawaidrana** [comment]
But still getting that error after npm install, just want to make it clear.

**Comment by eouia** [comment]
Hmmm. it seems node module `open` problem. Try `npm install --save open` in MMM-GooglePhotos directory then try again.

**Comment by nawaidrana** [comment]
Just tried command, it ran successfully with a message of open@6.4.0 but when I run npm auth_and_test.js, still getting same error. I also tried the electron rebuild, but same error when I run js.

**Comment by eouia** [comment]
What is your node version? `open/index.js` is using ES6 style script. So it might probablly become an issue on old system.

**Comment by nawaidrana** [comment]
How do I check node version and how do I update it if needed?

**Comment by eouia** [comment]
In terminal,
```sh
node -v
```


`...` is called as `rest` or `spread` operator. In this case, it is `spread` operator and supported from node version 6.4.0

**Comment by nawaidrana** [comment]
7.10.1

**Comment by eouia** [comment]
Hmmm... weird. All I can say is just that your node cannot understand `spread` operator, and that is not the issue of module itself.

**Comment by nawaidrana** [comment]
Ok I downgraded my node to 6.4.0 and I am getting a different error this time:
I am using magicmirror on raspberry pi, so not using it on windows.

node auth_and_test.js
/home/pi/test1/MMM-GooglePhotos/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/test1/MMM-GooglePhotos/auth.js:6:13)
    at Module._compile (module.js:556:32)

**Comment by eouia** [comment]
Hmmm.. I've tested to re-install on fresh RPI (RPI4, Raspbian Buster 2019-07-10, node v10.16.0, npm v6.9.0, gcc v7.3.0, MM v2.8.0) And there is no problem to install.

**Comment by eouia** [comment]
Have you any progress? I'll close this issue because there is no more feedback anymore. Feel free to reopen the issue when you have still the problem.
