### ISSUE TITLE
SyntaxError: Unexpected identifier (Mac OS) - when node auth_and_test.js 

### ISSUE THREAD

**Issue by adandl** [hermanho/MMM-GooglePhotos#41]
Hello!
Receive the following error-message when I try to authenticate (Google-Apps account - Not GMAIL) on MagicMirror under MacOS

/Users/xxxx/MagicMirror/modules/MMM-GooglePhotos/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxxx/MagicMirror/modules/MMM-GooglePhotos/auth.js:6:13)
    at Module._compile (module.js:570:32)

**Comment by eouia** [comment]
Maybe your nodeJS version is somewhat low (I think the `^^^^` mark would point `async`, right?)

**Comment by adandl** [comment]
I installed nodeJS just recently, but will try to update it tonight.
Will let you know if this fixes the issue

**Comment by adandl** [comment]
Hi,

not sure which version I had installed before, but now I installed this one:
https://nodejs.org/de/download/
And everything works now fine!
Thanks you for your help!!!

Kind regards
Albert
