### ISSUE TITLE
Syntax Error: Unexpected Identifier

### ISSUE THREAD

**Issue by lakyluke98** [hermanho/MMM-GooglePhotos#46]
Hi eouia!

I just tried to install this module but am not able to actually do so.
Everything worked fine but i can't start the mirror as i get the following syntax error:

`WARNING! Could not validate config file. Starting with default configuration. Please correct syntax errors at or above this line: /home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/open/index.js:16

const wslToWindowsPath = async path => {
                               ^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GooglePhotos/auth.js:6:13)
    at Module._compile (module.js:556:32)`

I've read through the other problems and tried the things you suggested to do in the other threads but had no luck.

I'm running following versions:

- Magic Mirror 2.9
- Node v10.18.0
- npm 6.13.4

I tried different Node versions: 8x, 10x or even 12x but still had no luck.
I hope that you might be able to help me with this problem.

Thanks in advance

Lukas!

**Comment by eouia** [comment]
Is really node v10? because your error message says your node version is quite low.
`async` is supported since node 7.6. 
Maybe your system might have more than 2 nodeJS installed locally. Check your node version again.
