### ISSUE TITLE
Photos did not refresh after a while

### ISSUE THREAD

**Issue by nagaculun** [hermanho/MMM-GooglePhotos#73]
After a while (about 2-3 hours), it did not refresh or load new picture. There are some error in the mm-error.log. Please help.

Thanks.

```
[2020-04-12 11:54:10.145] [ERROR]  (node:1495) UnhandledPromiseRejectionWarning: Error: getaddri
EAI_AGAIN photoslibrary.googleapis.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
[2020-04-12 11:54:10.154] [ERROR]  (node:1495) UnhandledPromiseRejectionWarning: Error: getaddri
EAI_AGAIN photoslibrary.googleapis.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
[2020-04-12 11:54:10.160] [ERROR]  (node:1495) UnhandledPromiseRejectionWarning: Unhandled promi
ejection. This error originated either by throwing inside of an async function without a catch b
, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2020-04-12 11:54:10.162] [ERROR]  (node:1495) UnhandledPromiseRejectionWarning: Unhandled promi
ejection. This error originated either by throwing inside of an async function without a catch b
, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2020-04-12 11:54:10.163] [ERROR]  (node:1495) [DEP0018] DeprecationWarning: Unhandled promise r
tions are deprecated. In the future, promise rejections that are not handled will terminate the
.js process with a non-zero exit code.
[2020-04-12 11:54:10.165] [ERROR]  (node:1495) [DEP0018] DeprecationWarning: Unhandled promise r
tions are deprecated. In the future, promise rejections that are not handled will terminate the
.js process with a non-zero exit code.
```

**Comment by eouia** [comment]
How many albums and photos in your target albums?

**Comment by nagaculun** [comment]
Just 1 album with 4000+ photos.

**Comment by eouia** [comment]
EAI_AGAIN is a DNS lookup timed out error, which means it is a network connectivity error or proxy related error. 
First, you need to confirm your network connection is stable. Your DNS server also might not be stable. 

Let me explain simply; When the module tries to connect `photoslibrary.googleapis.com`, sometimes your DNS server of internet provider(Or your own set) couldn't find a proper address in time. Or losing connection.

Sorry, nothing to do for me at this moment. I can add a feature of logging some graceful message, but that's all.

**Comment by nagaculun** [comment]
I use google dns server. I will poke around as well. If you could provide some points on the logging, that would be great.

Btw, good job on the modules. I loved it and thank you for it.

**Comment by eouia** [comment]
Or... experimental way which I cannot guarantee...

Open `package.json` of MagicMirror
Then go to line 7.
https://github.com/MichMich/MagicMirror/blob/447c0bffdcd2667c2d982cd2a1e5a7d43e45f112/package.json#L7

Then modify 
```js
"start": "DISPLAY=\"${DISPLAY:=:0}\" ./node_modules/.bin/electron js/electron.js",
```
to
```js
"start": "set UV_THREADPOOL_SIZE=16 & DISPLAY=\"${DISPLAY:=:0}\" ./node_modules/.bin/electron js/electron.js",
```
You can try `16` to another value like 32 or 64. But I'm not sure which value will be good.

**Comment by nagaculun** [comment]
Will try that and let you know. Thanks.

**Comment by nagaculun** [comment]
I changed to 16 but no different. Now the value is 32; and I got error 403. Attached is the console log. It error-ed out after 9 updates.

![image](https://user-images.githubusercontent.com/11765657/79699857-e33d7a00-8246-11ea-8fa1-dd88eb7827ff.png)

**Comment by eouia** [comment]
Ok, the Experimental way is not proper. As I've said before, there is not much things to do for your symptom. Anyway, I'll look inside more.  (Check to confirm your internet connection stable)

**Comment by nagaculun** [comment]
The internet connection should be no issue. Other modules load fine. Beside, the photos are showing (about 10) then error. How version 2 different with version 1?

**Comment by eouia** [comment]
Nothing much different logically. If you possible, send me config.js and entire backend log

**Comment by maciekczwa** [comment]
I have the same problem
After a while it stops working
Logs attached
`[2020-04-21 18:12:42.211] [ERROR]  (node:7783) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (/home/dietpi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/dietpi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/dietpi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-04-21 18:12:42.219] [ERROR]  (node:7783) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (/home/dietpi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/dietpi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/dietpi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
[2020-04-21 18:12:42.221] [ERROR]  (node:7783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2020-04-21 18:12:42.222] [ERROR]  (node:7783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[2020-04-21 18:12:42.223] [ERROR]  (node:7783) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-04-21 18:12:42.224] [ERROR]  (node:7783) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by nagaculun** [comment]
where is the backend log ? .pm2/logs files ?

**Comment by eouia** [comment]
@maciekczwa 
It's not the same error. Because your error code is 500 and it has different meaning. Anyway I'll look inside, at least to get more kind graceful logging.

**Comment by maciekczwa** [comment]
Yeah I see it is not the same, but I think it should handle the errors gracefully, it should retry after some time or just ignore the error. Now when the network error / server error happens the photos are not changing anymore.

**Comment by Ra7t0r** [comment]
Same here.
The module starts and works perfectly, but after some time does not displaying photos at all.

Here is the error code I get when issuing the `pm2 log mm` command

`0|mm | [2020-04-28 16:57:37.882] [ERROR] (node:7279) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. 0|mm | [2020-04-28 16:59:05.210] [ERROR] (node:7560) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. 0|mm | [2020-04-28 18:18:27.667] [ERROR] (node:9637) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. 0|mm | [2020-04-28 18:19:02.709] [ERROR] (node:9917) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. 0|mm | [2020-04-28 19:02:23.091] [ERROR] (node:11312) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. 0|mm | [2020-04-28 19:02:44.920] [ERROR] (node:11312) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503 0|mm | at createError (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/createError.js:16:15) 0|mm | at settle (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/settle.js:17:12) 0|mm | at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/adapters/http.js:236:11) 0|mm | at IncomingMessage.emit (events.js:187:15) 0|mm | at endReadableNT (_stream_readable.js:1090:12) 0|mm | at process._tickCallback (internal/process/next_tick.js:63:19) 0|mm | [2020-04-28 19:02:44.928] [ERROR] (node:11312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2) 0|mm | [2020-04-28 19:02:44.929] [ERROR] (node:11312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Any suggestions?
Thanks

**Comment by RoggerFabri** [comment]
I'm getting 403 for some requests, the connection is reliable and RPI is cable connected to the router, using Google DNS. Any ideas?

**Comment by eouia** [comment]
No idea. 403 error means you are not allowed. I need more detailed log to diagnose.

And guys, your symptoms are looking similarly but have all different reasons. So I want to you guys post your own issue. Each error code needs different approach. I cannot provide any single magic bullet for all kinds of errors.
