### ISSUE TITLE
Module stops working after a while.

### ISSUE THREAD

**Issue by Ra7t0r** [hermanho/MMM-GooglePhotos#77]
Hello.
I installed the module today and it’s pretty amazing.
Although I have an issue. The module starts and works perfectly, but after some time does not displaying photos at all.

Here is the error code I get when issuing the `pm2 log mm` command

`0|mm       | [2020-04-28 16:57:37.882] [ERROR]  (node:7279) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
0|mm       | [2020-04-28 16:59:05.210] [ERROR]  (node:7560) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
0|mm       | [2020-04-28 18:18:27.667] [ERROR]  (node:9637) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
0|mm       | [2020-04-28 18:19:02.709] [ERROR]  (node:9917) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
0|mm       | [2020-04-28 19:02:23.091] [ERROR]  (node:11312) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
0|mm       | [2020-04-28 19:02:44.920] [ERROR]  (node:11312) UnhandledPromiseRejectionWarning: Error: Request failed with status code 503
0|mm       |     at createError (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/createError.js:16:15)
0|mm       |     at settle (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/core/settle.js:17:12)
0|mm       |     at IncomingMessage.handleStreamEnd (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/axios/lib/adapters/http.js:236:11)
0|mm       |     at IncomingMessage.emit (events.js:187:15)
0|mm       |     at endReadableNT (_stream_readable.js:1090:12)
0|mm       |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|mm       | [2020-04-28 19:02:44.928] [ERROR]  (node:11312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
0|mm       | [2020-04-28 19:02:44.929] [ERROR]  (node:11312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Any suggestions?
Thanks

**Comment by Ra7t0r** [comment]
Already Created. Removed
