### ISSUE TITLE
Not loading photos

### ISSUE THREAD

**Issue by jedcrisp** [hermanho/MMM-GooglePhotos#90]
I am pretty new to this. I have read through every issues that has been closed to try and find my issue. I was able to fix somethings thanks to this.  I am still unable to get photos to show up when i start MM.  I generated a token and connected, and nothing happens.  This hapens when i try auth_and_test.js

pi@raspberrypi:~/MagicMirror/modules/default/MMM-GooglePhotos $ node auth_and_test.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/pi/MagicMirror/modules/default/MMM-GooglePhotos/auth_and_test.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

I am not sure what to do from her. I assume I am missing something, but do not what specifically or how to add it

**Comment by jedcrisp** [comment]
After watching some youtube videos and tinkering some more, it looks like I have everything set up the same way others have and it worked for them.  I have created the files needed, enabled API, generated token and created an album, but when i run MM it never loads any photos from the album
